version: '3.8'

services:
  base:
    image: edufolly/work-with-secrets:${VERSION:-0.0.6K}
    secrets:
      - my-secret
      - MY_UPPERCASE_SECRET
    ports:
      - ${EXPOSED_PORT:-8080}:8080
    deploy:
      mode: replicated
      replicas: 1

secrets:
  my-secret:
    external: true
  MY_UPPERCASE_SECRET:
    external: true
